packages:
  - apps/*
  - content/*
  - '!content/tests'
  - packages/*

allowBuilds:
  '@maplibre/maplibre-gl-native': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@maplibre/maplibre-gl-native'
  - esbuild
  - sharp
