import type { InterfaceConfig } from './types';

/** English defaults for every app control. Override with interface.text in slides.config.yml.
 * Keep {placeholders} when translating labels with dynamic content. */
export const interfaceDefaults = {
  startButton: 'Start',
  open: 'Open',
  close: 'Close',
  expand: 'Expand',
  collapse: 'Collapse',
  show: 'Show',
  hide: 'Hide',
  sections: 'Sections',
  chapterNumber: 'Chapter {number}',
  chapterCountSingular: '{count} chapter in this slideshow',
  chapterCountPlural: '{count} chapters in this slideshow',
  madeWith: 'Made with',
  productName: 'Allmaps Slides',
  navigation: 'Slideshow navigation',
  options: 'Slideshow options',
  previousChapter: 'Previous chapter',
  previousChapterTitle: 'Previous chapter: {title}',
  nextChapter: 'Next chapter',
  nextChapterTitle: 'Next chapter: {title}',
  chapterPosition: 'Chapter {current} of {total}',
  chapterCounter: '{current} / {total}',
  slideshowProgress: 'Slideshow progress',
  mapLayers: 'Map layers',
  backgroundMap: 'Background map',
  chapters: 'Table of contents',
  lightMode: 'Light mode',
  darkMode: 'Dark mode',
  hideSidePanel: 'Hide side panel',
  showSidePanel: 'Show side panel',
  backToMain: 'Back to main slideshow',
  backToTitle: 'Back to {title}',
  scrollToTop: 'Back to top',
  credits: 'Credits',
  noCredits: 'No credits have been provided for this slideshow.',
  expandAll: 'Expand all',
  collapseAll: 'Collapse all',
  slides: 'Slides',
  subslideshows: 'Subslideshows',
  slideCountSingular: '{count} slide',
  slideCountPlural: '{count} slides',
  slideCard: '{title}, slide {current} of {total}',
  slideshowCard: '{title}, {count}',
  mapCount: 'Show map layers ({count})',
  mapCountSingular: '{count} map',
  mapCountPlural: '{count} maps',
  mapLayer: 'Map layer {count}',
  imageLayer: 'Image layer',
  georeferenceAnnotation: 'Georeference annotation',
  noLayers: 'No map layers for this slide',
  visibleLayerSingular: '{count} map layer visible',
  visibleLayerPlural: '{count} map layers visible',
  hiddenLayerCount: '{visible}, {count} hidden',
  openInAllmaps: 'Open in Allmaps',
  zoomToMapLayer: 'Zoom to map layer',
  noWarpedMaps: 'This slide does not use any warped maps.',
  showTextPanel: 'Show text panel',
  reduceTextPanel: 'Reduce text panel',
  expandTextPanel: 'Expand text panel',
  panelDragHint: 'Drag up to expand or down to hide',
  panelDragInstructions: 'Drag up to expand the text panel or down to hide it. Use the up and down arrow keys to resize.',
  map: 'Map',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  resetNorth: 'Reset north',
  image: 'Image',
  enlargeImage: 'Enlarge image: {title}',
  imageZoom: 'Image zoom',
  loadingImage: 'Loading image…',
  imageLoadError: 'The IIIF image could not be loaded.',
  tryAgain: 'Try again',
  downloadPreview: 'Download image preview',
  downloadView: 'Download image view',
  previewDownloadError: 'The image preview could not be downloaded.',
  viewDownloadError: 'The image view could not be downloaded.',
} as const;

export type InterfaceKey = keyof typeof interfaceDefaults;
export type InterfaceText = (key: InterfaceKey, values?: Record<string, string | number>) => string;
export const createInterfaceText = (config: () => InterfaceConfig | undefined = () => undefined): InterfaceText =>
  (key, values = {}) => {
    const settings = config();
    const legacy = settings?.startScreen as Record<string, string | undefined> | undefined;
    const template = settings?.text?.[key] ?? legacy?.[key] ?? interfaceDefaults[key];
    return template.replace(/\{(\w+)\}/g, (match, name) => values[name] === undefined ? match : String(values[name]));
  };
