type Direction = "previous" | "next";

/** Touch swipes share the navigator's normal chapter navigation callback. */
export function navigatorSwipe(element: HTMLElement, onSwipe: (direction: Direction) => void) {
  const mobile = element.ownerDocument.defaultView!.matchMedia("(max-width: 767px)");
  let gesture: { id: number; x: number; y: number; dragging: boolean } | undefined;
  let suppressClick = false;

  const start = (event: PointerEvent) => {
    suppressClick = false;
    if (!mobile.matches || event.pointerType !== "touch" || !event.isPrimary || gesture) return;
    gesture = { id: event.pointerId, x: event.clientX, y: event.clientY, dragging: false };
  };

  const move = (event: PointerEvent) => {
    if (!gesture || gesture.id !== event.pointerId) return;
    const x = Math.abs(event.clientX - gesture.x);
    const y = Math.abs(event.clientY - gesture.y);
    if (!gesture.dragging) {
      if (Math.max(x, y) < 10) return;
      // Leave vertical gestures to the browser and the text panel.
      if (x <= y * 1.25) { gesture = undefined; return; }
      gesture.dragging = true;
      element.setPointerCapture(event.pointerId);
    }
    suppressClick = true;
    event.preventDefault();
  };

  const finish = (event: PointerEvent, cancelled = false) => {
    if (!gesture || gesture.id !== event.pointerId) return;
    const finished = gesture;
    gesture = undefined;
    if (element.hasPointerCapture(event.pointerId)) element.releasePointerCapture(event.pointerId);
    const x = event.clientX - finished.x;
    const y = event.clientY - finished.y;
    if (cancelled || !mobile.matches || !finished.dragging || Math.abs(x) < 40 || Math.abs(x) <= Math.abs(y) * 1.25) return;
    onSwipe(x < 0 ? "next" : "previous");
  };
  const end = (event: PointerEvent) => finish(event);
  const cancel = (event: PointerEvent) => finish(event, true);
  const lostCapture = (event: PointerEvent) => {
    // A touch starts with implicit capture on the tapped button or icon.
    // Its lost-capture event bubbles here when we take over the swipe.
    if (event.target === element) cancel(event);
  };
  const click = (event: MouseEvent) => {
    // Consume the click generated by a swipe without changing ordinary taps
    // or keyboard activation. The next pointerdown starts a fresh gesture.
    if (!suppressClick || event.detail === 0) return;
    suppressClick = false;
    event.preventDefault();
    event.stopImmediatePropagation();
  };

  element.addEventListener("pointerdown", start);
  element.addEventListener("pointermove", move);
  element.addEventListener("pointerup", end);
  element.addEventListener("pointercancel", cancel);
  element.addEventListener("lostpointercapture", lostCapture);
  element.addEventListener("click", click, true);
  return {
    update(callback: typeof onSwipe) { onSwipe = callback; },
    destroy() {
      if (gesture && element.hasPointerCapture(gesture.id)) element.releasePointerCapture(gesture.id);
      element.removeEventListener("pointerdown", start);
      element.removeEventListener("pointermove", move);
      element.removeEventListener("pointerup", end);
      element.removeEventListener("pointercancel", cancel);
      element.removeEventListener("lostpointercapture", lostCapture);
      element.removeEventListener("click", click, true);
    },
  };
}
